version: '3'
services:

  Aesthetic-Startpage:
    image: nginx
    volumes:
      - $HOME/.cache/Aesthetic-Startpage/images/:/usr/share/nginx/html/images/
      - $HOME/.cache/Aesthetic-Startpage/themes/:/usr/share/nginx/html/themes/
      - $HOME/.cache/Aesthetic-Startpage/index.html:/usr/share/nginx/html/index.html
      - $HOME/.cache/Aesthetic-Startpage/pywal_colors.css:/usr/share/nginx/html/pywal_colors.css
      - $HOME/.cache/Aesthetic-Startpage/default.conf:/etc/nginx/conf.d/default.conf # modified conf to disable page caching :)
    ports:
    - "8765:80"
    environment:
    - NGINX_PORT=80
    restart: unless-stopped
